/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Aliaksandr.melas (https://sketchfab.com/alexandr.melas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/starry-galaxy-sky-hdri-background-photosphere-e85426f6c246446a87c01e3f8357d98d
Title: Starry galaxy sky HDRi background photosphere
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from '@react-three/fiber';

import scene from '../assets/3d/dark-sky.glb';

const DarkSky = ({isRotating, ...props}) => {
  const { nodes, materials } = useGLTF(scene);

  const skyRef = useRef();

  useFrame((_, delta) => {
    if(isRotating) {
      skyRef.current.rotation.y += 0.15*delta;
    }
  })

  return (
    <group dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={308.781}>
        <mesh ref={skyRef}
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

export default DarkSky;
